name = "TopoPlots"
uuid = "2bdbdf9c-dbd8-403f-947b-1a4e0dd41a7a"
authors = ["Benedikt Ehinger", "Simon Danisch", "Beacon Biosignals, Inc."]
version = "0.2.4"

[deps]
CloughTocher2DInterpolation = "b70b374f-000b-463f-88dc-37030f004bd0"
Delaunator = "466f8f70-d5e3-4806-ac0b-a54b75a91218"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NaturalNeighbours = "f16ad982-4edb-46b1-8125-78e5a8b5a9e6"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ScatteredInterpolation = "3f865c0f-6dca-5f4d-999b-29fe1e7e3c92"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Aqua = "0.8"
CairoMakie = "0.13, 0.14"
CloughTocher2DInterpolation = "0.1"
CondaPkg = "0.2"
Delaunator = "0.1"
Dierckx = "0.5"
FileIO = "1"
GeometryBasics = "0.4, 0.5"
ImageIO = "0.6"
InteractiveUtils = "1"
LinearAlgebra = "1"
Makie = "0.24"
NaturalNeighbours = "1"
Parameters = "0.12"
PrecompileTools = "1"
PyMNE = "0.2"
PythonCall = "0.9"
PythonPlot = "1"
ScatteredInterpolation = "0.3.6"
StaticArrays = "1"
Statistics = "1"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
PyMNE = "6c5003b2-cbe8-491c-a0d1-70088e6a0fd6"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "CairoMakie", "CondaPkg", "FileIO", "ImageIO", "PyMNE", "PythonCall", "PythonPlot", "StaticArrays", "Test"]
